name: signal-cli # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple terminal user interface for Signal. # 79 char long summary
description: |
  scli is a simple terminal user interface for Signal. It uses signal-cli and urwid.

confinement: devmode # use 'strict' once you have the right plugs and slots
base: core18

parts:
  signal-cli:
    plugin: dump
    source: https://github.com/AsamK/signal-cli/releases/download/v0.6.8/signal-cli-0.6.8.tar.gz
    stage-packages: [openjdk-8-jre, libunixsocket-java]

  scli:
    plugin: dump
    source: https://github.com/isamert/scli.git
    organize:
      scli: bin/
    stage-packages: [python3, python3-urwid, qrencode]

apps:
  signal-cli:
    command: bin/signal-cli
    plugs: [network, home]
    environment:
      JAVA_HOME: "${SNAP}/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}"

  scli:
    command: bin/scli
    plugs: [home]

  qrencode:
    command: usr/bin/qrencode
